[package]
name = "jastery"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.10.0"
image = "0.24"
uuid = "1.3"
rand = "0.8"
pathfinding = "4.2.1"
chrono = "0.4"
tracing-subscriber = "0.3.16"
tracing-appender = "0.2"

[profile.release]
debug = true